FROM almalinux:9
LABEL first_name="Moka" \
      Second_name="Ganesh" \
      learning="Devsecops"
# Lables are used for filtering. These keep meta data. this doesn't provide any functinality to image.
