# in docker conatiner cd command will not work.This instaruyction is used to change the current working dir.
FROM almalinux:9
RUN mkdir /tmp/dockers
WORKDIR /tmp/dockers
RUN pwd                
# display present working dir.
CMD ["sleep", "100"]



