FROM almalinux:9
RUN dnf install nginx -y  # this will run while creation of image.
CMD ["nginx","-g","daemon off;"] # this keep the nginx run in foreground.This will run while cretaion on container.
