FROM almalinux:9
ENV name="ganesh" \
    age="25"
RUN dnf install nginx -y 
CMD ["nginx", "-g", "daemon off;"] 

#ENV instruction is used to setup environment variables. it can be used inside the containers.
